import type { IngestedContent } from "@/src/lib/ai/schemas/ingested-content";
import { withSystemPrompt } from "./system";

export function buildAnalyzePrompt(ingested: IngestedContent): string {
  const sectionsText = ingested.contentSections
    .map((s) => `## ${s.heading}\n${s.body}`)
    .join("\n\n");

  return withSystemPrompt(`## YOUR TASK: Originality Gap Analysis

Analyze the following content and score it on 5 originality signals. Your goal is to identify how much genuine information gain this content provides vs. what already exists in general market discourse.

TITLE: ${ingested.title}
WORD COUNT: ${ingested.metadata.wordCount}
${ingested.metadata.author ? `AUTHOR: ${ingested.metadata.author}` : ""}

CONTENT:
${sectionsText}

---

Score each of the following 5 signals on a scale of 0-10. For each signal, quote specific evidence from the text and give one actionable recommendation.

## SCORING RUBRIC

### 1. proprietary_data
Does this content contain original data, research, surveys, or internal metrics?
- 0-3 (Low): No original data — relies entirely on third-party stats or no data at all
- 4-6 (Medium): References some data but it is publicly available or vague
- 7-10 (High): Contains original research, internal metrics, proprietary surveys, or first-party data

### 2. first_person_specificity
Does the author share specific personal experiences, named clients, or concrete case studies?
- 0-3 (Low): Generic advice with no personal grounding ("many companies find that...")
- 4-6 (Medium): Some personal framing but lacks specific names, numbers, or outcomes
- 7-10 (High): Named examples, specific dollar amounts, dates, client names, or personal transformation stories

### 3. verifiable_claims
Are the claims specific enough to be checked or cited?
- 0-3 (Low): Vague assertions ("AI is changing everything") — nothing to fact-check
- 4-6 (Medium): Some specific claims but missing sources or years
- 7-10 (High): Specific statistics with sources, named studies, or falsifiable predictions

### 4. non_obvious_conclusions
Does the content reach conclusions that contradict conventional wisdom or synthesize ideas in a genuinely new way?
- 0-3 (Low): Restates what everyone already knows ("You need to post consistently")
- 4-6 (Medium): Slightly contrarian but not surprising to an informed reader
- 7-10 (High): Genuinely counterintuitive, challenges dominant narratives with evidence

### 5. depth_score
Does the content explain the WHY and HOW, not just the WHAT?
- 0-3 (Low): Surface-level overview — could be generated by any AI with no domain knowledge
- 4-6 (Medium): Some explanation of mechanisms but lacks nuance or second-order effects
- 7-10 (High): Explains underlying mechanisms, edge cases, tradeoffs, or causal chains in depth

---

## GRADING
Compute overall_score as the average of all 5 signal scores.
Assign grade: A (8.0-10), B (6.0-7.9), C (4.0-5.9), D (2.0-3.9), F (0-1.9)

Classify the content:
- original_research: New data or experiments
- expert_commentary: Expert opinion without original data
- curated_synthesis: Aggregates others' ideas well
- derivative_rehash: Summarizes what's already out there
- generic_advice: Template-level content with no domain specificity

Identify:
- strongest_asset: The single best thing about this content's originality
- biggest_gap: The most important missing element for higher information gain
- enrichment_suggestions: 1-5 specific, actionable suggestions to improve originality

Respond with a valid JSON object matching the required schema.`);
}
